import { OrderStatus } from "@/utils/Types";
import { CheckCircle2, Clock, Package, Truck, XCircle } from "lucide-react";

export const UILabels = {
  SECTIONS: {
    BRAND_HIGHLIGHT_BLOCK: "Brand Highlight Block",
    CONTACT_METHODS: "Contact Methods",
    COPYRIGHT__BOTTOM_TEXT: "Copyright / Bottom Text",
    CORE_VALUES_BANNER: "Core Values Banner",
    CORE_VALUES_LIST: "Core Values List",
    CURATED_DISCOVERY_PRODUCTS_SLIDER: "Curated Discovery Products Slider",
    FOOTER_COLUMNS: "Footer Columns",
    HERO_BLOCK: "Hero Block",
    HERO_BLOCK_LEGACY__USED_IF_NO_CAROUSEL_SLIDES_ABOVE:
      "Hero Block (Legacy — used if no carousel slides above)",
    HERO_CAROUSEL_SLIDES: "Hero Carousel Slides",
    CATEGORIES_SECTION: "Categories Section",
    INTERACTIVE_HERO_OPTIONS_ENHANCED: "Interactive Hero Options (Enhanced)",
    MIDDLE_PROMO_BANNER: "Middle Promo Banner",
    MISSION_DELIVERABLES: "Mission Deliverables",
    MISSION_SECTION: "Mission Section",
    NAVIGATION_LINKS: "Navigation Links",
    NEW_ARRIVALS__4_GRID_LAYOUT: "New Arrivals — 4 Grid Layout",
    NEWSLETTER_BLOCK: "Newsletter Block",
    SCARCITY__URGENCY_TIMER_BLOCK: "Scarcity & Urgency Timer Block",
    SHOPPABLE_LOOKBOOK_SECTION: "Shoppable Lookbook Section",
    STORE_PAGE_PROMOTIONAL_BANNER: "Store Page Promotional Banner",
    THOUGHTS__FOUNDER: "Thoughts & Founder",
    TRUST__SOCIAL_PROOF_SECTION: "Trust & Social Proof Section",
    URGENT_PROMO__COUNTDOWN_TIMER: "Urgent Promo & Countdown Timer",
    // Navbar sections
    NAVBAR_LOGO: "Logo & Brand Identity",
    NAVBAR_BEHAVIOR: "Navbar Behavior",
    NAVBAR_SEARCH_BAR: "Search Bar",
    NAVBAR_UTILITIES: "Utility Icons (Account / Wishlist / Cart)",
    NAVBAR_NAVIGATION_ITEMS: "Navigation Items (L1 Links)",
  },
  FIELDS: {
    ACTION_BUTTON_LINK_URL: "Action Button Link (URL)",
    ACTION_BUTTON_TEXT: "Action Button Text",
    ADD_CARD: "Add Card",
    ADD_COLUMN: "Add Column",
    ADD_HOTSPOT: "Add Hotspot",
    ADD_LINK: "Add Link",
    ADD_METHOD: "Add Method",
    ADD_SLIDE: "Add Slide",
    ADD_STAT: "Add Stat",
    ADD_TESTIMONIAL: "Add Testimonial",
    ADD_TRUST_BADGE: "Add Trust Badge",
    ADD_VALUE: "Add Value",
    ALERT_BAR_BACKGROUND_COLOR: "Alert Bar Background Color",
    ALERT_BAR_TEXT_COLOR: "Alert Bar Text Color",
    AVATAR_IMAGE_URL_OPTIONAL: "Avatar Image URL (Optional)",
    BACKGROUND_IMAGE: "Background Image",
    BACKGROUND_STYLE: "Background Style",
    BADGE_TITLE: "Badge Title",
    BANNER_ACTION_LINK_URL: "Banner Action Link (URL)",
    BANNER_DESCRIPTION: "Banner Description",
    BANNER_DISPLAY_TYPE: "Banner Display Type",
    BANNER_TITLE: "Banner Title",
    BOTTOM_TEXT: "Bottom Text",
    BUTTON_TEXT: "Button Text",
    CTA_ACTION_BUTTON_LINK_URL: "CTA Action Button Link (URL)",
    CTA_ACTION_BUTTON_TEXT: "CTA Action Button Text",
    CARD_BACKGROUND_COLOR_OVERRIDES_AUTODETECT_FROM_IMAGE:
      "Card Background Color (overrides auto-detect from image)",
    CARD_BACKGROUND_COLOR_OVERRIDES_AUTODETECT:
      "Card Background Color (overrides auto-detect)",
    COLUMN_HEADER: "Column Header",
    CURATION_CATEGORY_TYPE: "Curation Category Type",
    CUSTOMER_NAME: "Customer Name",
    DESCRIPTION: "Description",
    DETAILS__VALUE: "Details / Value",
    DISCOVERY_SECTION_HEADING: "Discovery Section Heading",
    EXPIRATION_DATE__TIME: "Expiration Date & Time",
    EYEBROW_TAG__SUBTEXT: "Eyebrow Tag / Subtext",
    FOUNDER_NAME: "Founder Name",
    FOUNDER_PHOTO: "Founder Photo",
    FOUNDER_TITLE__ROLE: "Founder Title / Role",
    HERO_BACKGROUND_IMAGE: "Hero Background Image",
    HERO_BANNER_IMAGE: "Hero Banner Image",
    HERO_SUBTITLE: "Hero Subtitle",
    HERO_TITLE: "Hero Title",
    HIGHLIGHT_BANNER_IMAGE: "Highlight Banner Image",
    HIGHLIGHT_BUTTON_TEXT: "Highlight Button Text",
    HIGHLIGHT_DESCRIPTION: "Highlight Description",
    HIGHLIGHT_EYEBROW__SUBTITLE: "Highlight Eyebrow / Subtitle",
    HIGHLIGHT_TITLE: "Highlight Title",
    ICON_LUCIDE_NAME: "Icon (Lucide name)",
    LABEL: "Label",
    LAYOUT_STYLE: "Layout Style",
    LOOKBOOK_SECTION_TITLE: "Lookbook Section Title",
    LOOKBOOK_SUBTITLE__DESCRIPTION: "Lookbook Subtitle / Description",
    LUCIDE_ICON_NAME: "Lucide Icon Name",
    MAIN_LOOKBOOK_IMAGE: "Main Lookbook Image",
    MARKETING_ALERT_BANNER_TEXT: "Marketing Alert Banner Text",
    MARKETING_ALERT_TEXT_MESSAGE: "Marketing Alert Text Message",
    MISSION_IMAGE: "Mission Image",
    MISSION_STATEMENT: "Mission Statement",
    MISSION_TITLE: "Mission Title",
    NEWSLETTER_BUTTON_TEXT: "Newsletter Button Text",
    NEWSLETTER_DESCRIPTION: "Newsletter Description",
    NEWSLETTER_EYEBROW__TAG: "Newsletter Eyebrow / Tag",
    NEWSLETTER_SUCCESS_MESSAGE: "Newsletter Success Message",
    NEWSLETTER_TERMS_DISCLAIMER: "Newsletter Terms Disclaimer",
    NEWSLETTER_TITLE: "Newsletter Title",
    PROMO_BANNER_IMAGE: "Promo Banner Image",
    PROMO_CARD_BACKGROUND_IMAGE: "Promo Card Background Image",
    LOCATION: "Location",
    ROLE__DESIGNATION: "Role / Designation",
    SECTION_BACKGROUND_COLOR: "Section Background Color",
    SECTION_BACKGROUND_COLOR_FALLBACK_IF_NO_IMAGE_OR_TRANSPARENT:
      "Section Background Color (fallback if no image or transparent)",
    SECTION_IMAGE: "Section Image",
    SECTION_TITLE: "Section Title",
    SHORT_DESCRIPTION: "Short Description",
    SLIDE_BACKGROUND_COLOR_USED_WHEN_STYLE_IS_CUSTOM:
      "Slide Background Color (used when style is Custom)",
    SLIDE_BANNER_IMAGE: "Slide Banner Image",
    SOCIAL_PROOF_HEADER_TITLE: "Social Proof Header Title",
    STAT_LABEL_EG_PRODUCTS: "Stat Label (e.g. Products)",
    STAT_VALUE_EG_500: "Stat Value (e.g. 500+)",
    SUBTITLE: "Subtitle",
    SUBTITLE_SMALL_LABEL_ABOVE_TITLE: "Subtitle (small label above title)",
    SUBTITLE__TAGLINE: "Subtitle / Tagline",
    TAGLINE: "Tagline",
    TESTIMONIAL_QUOTE__TEXT: "Testimonial Quote / Text",
    TIMER_HEADING_TITLE: "Timer Heading Title",
    TITLE: "Title",
    URL_PATH: "URL Path",
    VIDEO_BACKGROUND_URL_MP4_FORMAT: "Video Background URL (MP4 Format)",
    VIDEO_HERO_BUTTON_LINK_URL: "Video Hero Button Link (URL)",
    VIDEO_HERO_BUTTON_TEXT: "Video Hero Button Text",
    VIDEO_HERO_DESCRIPTION: "Video Hero Description",
    VIDEO_HERO_EYEBROW__TAG: "Video Hero Eyebrow / Tag",
    VIDEO_HERO_TITLE: "Video Hero Title",
    ADD_NAV_ITEM: "Add Nav Item",
    NAV_LOGO_SRC: "Logo Image URL",
    NAV_LOGO_ALT: "Logo Alt Text",
    NAV_LOGO_HREF: "Logo Link (href)",
    NAV_LOGO_ALIGNMENT: "Logo Alignment",
    NAV_POSITION: "Navbar Scroll Behavior",
    NAV_SHOW_SHADOW: "Show Shadow",
    NAV_SHOW_BORDER: "Show Bottom Border",
    NAV_SEARCH_VISIBLE: "Show Search Bar",
    NAV_SEARCH_PLACEHOLDER: "Search Placeholder Text",
    NAV_SEARCH_ENDPOINT: "Search Route / Endpoint",
    NAV_SHOW_ACCOUNT: "Show Account Icon",
    NAV_SHOW_WISHLIST: "Show Wishlist Icon",
    NAV_SHOW_CART: "Show Cart Icon",
    NAV_ITEM_LABEL: "Nav Item Label",
    NAV_ITEM_HREF: "Nav Item URL",
    NAV_ITEM_HAS_MEGA: "Has Mega-Menu Dropdown",
    ASSOCIATED_CATEGORY: "Associated Category",
    LINK_TYPE: "Link Type",
    MEGA_MENU_DISPLAY_SOURCE: "Mega Menu Display Source",
    PARENT_CATEGORY_SOURCE: "Parent Category (Source)",
    HIERARCHICAL_DEPTH: "Hierarchical Depth",
    PROMOTION_TITLE: "Promotion Title",
    PROMOTION_SUBTITLE: "Promotion Subtitle",
    PROMOTION_LINK_TARGET_URL: "Promotion Link Target URL",
    PROMOTION_BANNER_IMAGE: "Promotion Banner Image",
  },
};

export const STATUS_CONFIG: Partial<
  Record<
    OrderStatus,
    {
      label: string;
      className: string;
      icon: React.ComponentType<any>;
      dot: string;
    }
  >
> = {
  [OrderStatus.PENDING]: {
    label: "Pending",
    className: "bg-amber-50 text-amber-700 border border-amber-200",
    icon: Clock,
    dot: "bg-amber-400",
  },
  [OrderStatus.PROCESSING]: {
    label: "Processing",
    className: "bg-blue-50 text-blue-700 border border-blue-200",
    icon: Package,
    dot: "bg-blue-400",
  },
  [OrderStatus.SHIPPED]: {
    label: "Shipped",
    className: "bg-violet-50 text-violet-700 border border-violet-200",
    icon: Truck,
    dot: "bg-violet-400",
  },
  [OrderStatus.DELIVERED]: {
    label: "Delivered",
    className: "bg-emerald-50 text-emerald-700 border border-emerald-200",
    icon: CheckCircle2,
    dot: "bg-emerald-400",
  },
  [OrderStatus.CANCELLED]: {
    label: "Cancelled",
    className: "bg-red-50 text-red-700 border border-red-200",
    icon: XCircle,
    dot: "bg-red-400",
  },
} as const;
